name: 🚀 Build & Deploy Angular (compagnie-blin) to IONOS (SCP)

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Cache node modules
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm ci

      - name: Build Angular app
        run: npm run build -- --configuration production

      # === Déploiement via SCP (fonctionne avec mot de passe ou clé SSH) ===
      - name: Deploy files to IONOS using SCP
        uses: appleboy/scp-action@v0.1.6
        with:
          host: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          # Utilise password OU key (décommente la méthode que tu choisis)
          password: ${{ secrets.FTP_PASSWORD }}
          # key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          source: "dist/compagnie-blin/browser/*"
          target: "/htdocs/"        # racine de ton espace SFTP (équivalent de sftp://u.../)
          recursive: true
          strip_components: 0
